version: "3.9"  # optional since v1.27.0
services:
  rubicon_sql:
    container_name: rubicon_sql
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Rubicontask123
      
  web_api:
    depends_on:
      - rubicon_sql
    build: . # build the Docker image 
    container_name: web_api_application
    ports:
      - "5000:80"
